sites:
  - name: Ishaan Vastraa API
    url: https://pibuydangxcjtfyrxowh.supabase.co/auth/v1/health
    method: GET
    headers:
      - "apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBpYnV5ZGFuZ3hjanRmeXJ4b3doIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY4NjI1MDgsImV4cCI6MjA5MjQzODUwOH0.gONAavkf28tM2VGHnmIoaOFPtuxY9Wk7vIjNerHPXYc"

  - name: Prathva API
    url: https://stegucpumzijbuacqfbf.supabase.co/auth/v1/health
    method: GET
    headers:
      - "apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN0ZWd1Y3B1bXppamJ1YWNxZmJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk3MjU3NzYsImV4cCI6MjA5NTMwMTc3Nn0.1X03QO0UWAGWqdbHzhNQayNTqKms9fp6AAmeFbVEejw"

  - name: Deepika Trends API
    url: https://fgudetmtfxltohoqqxtg.supabase.co/auth/v1/health
    method: GET
    headers:
      - "apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZndWRldG10ZnhsdG9ob3FxeHRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODYzNzU2MTAsImV4cCI6MjEwMTk1MTYxMH0.qtMAvtSZ6uN_N7j0Ik6yahJylBcYSSxpxATLbYF54Nw"

owner: surendra-Gd
repo: client-uptime-monitor
